name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Copy files to public directory
      run: |
        cp index.html public/
        cp -r scripts public/
        cp -r styles public/
        cp -r assets public/
        cp README.md public/
        cp test-functionality.html public/
    
    - name: Deploy to Firebase Hosting (Preview)
      if: github.event_name == 'pull_request'
      run: firebase hosting:channel:deploy preview --project soccer-bet-pro --token ${{ secrets.FIREBASE_TOKEN }}
    
    - name: Deploy to Firebase Hosting (Production)
      if: github.ref == 'refs/heads/main'
      run: firebase deploy --only hosting --project soccer-bet-pro --token ${{ secrets.FIREBASE_TOKEN }}